

export const ICO_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_ICO_CONTRACT_ADDRESS;
export const CSP_PRICE = Number(process.env.NEXT_PUBLIC_CSP_PRICE);
export const OWNER_ADDRESS = process.env.NEXT_PUBLIC_OWNER_ADDRESS;
export const USDT_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_USDT_CONTRACT_ADDRESS;
